namespace StarWars5e.Models.Enums
{
    public enum EquipmentCategory
    {
        Unknown,
        Ammunition,
        Explosive,
        Weapon,
        Armor,
        Storage,
        AdventurePack,
        Communications,
        DataRecordingAndStorage,
        LifeSupport,
        Medical,
        WeaponOrArmorAccessory,
        Tool,
        Mount,
        Vehicle,
        TradeGood,
        Utility,
        GamingSet,
        MusicalInstrument,
        Droid,
        Clothing,
        Kit,
        AlcoholicBeverage,
        Spice
    }
}