namespace StarWars5e.Models.EnhancedItems
{
    public enum ItemModificationType
    {
        None,
        Armoring,
        Augment,
        Barrel,
        Conductor,
        Crystal,
        Cycler,
        Dataport,
        Edge,
        Emitter,
        EnergyChannel,
        EnergyCore,
        Grip,
        Lens,
        Matrix,
        Motherboard,
        Overlay,
        PowerCell,
        Processor,
        Projector,
        Reinforcement,
        Shielding,
        Stabilizer,
        Storage,
        Targeting,
        Underlay,
        VibratorCell,
        Other,
        Weave,
        Inlay
    }
}
